[build]
# FIXME: make this the target triple you want to compile for
# should be one of the triples listed below
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-nostdlib", "-C", "link-arg=-nostartfiles",
             "-C", "link-arg=-Wl,-Tlinker.ld,--build-id=none", "-C", "link-arg=-static"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-nostdlib", "-C", "link-arg=-nostartfiles",
             "-C", "link-arg=-Wl,-Tlinker.ld,--build-id=none", "-C", "link-arg=-static"]

[target.armv7a-none-eabi]
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-nostdlib",
             "-C", "link-arg=-Tlinker.ld", "-C", "link-arg=--build-id=none", "-C", "link-arg=-static",
             "-C", "link-arg=--strip-debug"]

[target.aarch64-unknown-none]
rustflags = ["-C", "link-self-contained=no", "-C", "link-arg=-nostdlib",
             "-C", "link-arg=-Tlinker.ld", "-C", "link-arg=--build-id=none", "-C", "link-arg=-static",
             "-C", "link-arg=--strip-debug"]

[target.mipsel-unknown-linux-musl]
rustflags = ["-C", "link-self-contained=no", "-C", "linker-flavor=ld.lld", "-C", "link-arg=--nostdlib",
             "-C", "link-arg=-Tlinker.ld", "-C", "link-arg=--static", "-C", "link-arg=--build-id=none",
             "-C", "link-arg=--discard-all", "-C", "link-arg=--gc-sections", "-C", "target-feature=+crt-static"]

[target.mips64el-unknown-linux-muslabi64]
rustflags = ["-C", "link-self-contained=no", "-C", "linker-flavor=ld.lld", "-C", "link-arg=--nostdlib",
             "-C", "link-arg=-Tlinker.ld", "-C", "link-arg=--static", "-C", "link-arg=--build-id=none",
             "-C", "link-arg=--discard-all", "-C", "link-arg=--gc-sections", "-C", "target-feature=+crt-static"]
